# https://www.gitpod.io/docs/config-gitpod-file

tasks:
  - name: run NEAR sandbox
    command: make docker_sandbox_start

  - name: build contracts
    init: |
      rustup target add wasm32-unknown-unknown 
      npm install
    command: make unittest && make stubtest && make sandboxtest

