[package]
name = "stub"
version = "0.2.0"
authors = ["mykle hansen for STATELESS <mykle@mykle.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[dependencies]
near-sdk = "3.1.0"

